# Generated by Django 4.1.7 on 2023-03-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_consumption', models.IntegerField()),
                ('engine_consumption', models.IntegerField()),
                ('electricity_consumption', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('ship_mass', models.IntegerField()),
                ('oxygen_consumption', models.IntegerField()),
                ('SH_start', models.IntegerField()),
                ('SH_end', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='API.waypoint')),
            ],
        ),
    ]
